### ISSUE TITLE
TypeError:  daemon.getBlockCount is not a function

### ISSUE THREAD

**Issue by leahcornelius** [TheDevMinerTV/Checkpoint-Generator#12]
/home/leo/Checkpoint-Generator/checkpoint_generator.js:20
daemon.getBlockCount().then(async (height) => {
       ^

TypeError: daemon.getBlockCount is not a function
    at Object.<anonymous> (/home/leo/Checkpoint-Generator/checkpoint_generator.js:20:8)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! checkpoint_generator@1.0.0 start: `node checkpoint_generator.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the checkpoint_generator@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/leo/.npm/_logs/2020-03-08T19_09_45_982Z-debug.log

**Comment by leahcornelius** [comment]
I think this is to do with a version bump
perhaps seting the turtlecoinrpc dependency to a lower level might fix this?

**Comment by leahcornelius** [comment]
yep, ill open a PR
